# Generated by Django 2.2.3 on 2019-07-18 03:31

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190713_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='topics',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
